# WanjPlayer CI
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools
        sudo apt-get install -y libwxgtk3.2-dev libwxbase3.2-1

    - name: Check wx-config
      run: wx-config --version

    - name: Configure CMake
      env:
        WX_CONFIG: /usr/bin/wx-config
        wxWidgets_CONFIGURATION: gtk3
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
