name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwxgtk3.2-dev gstreamer-1.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
